# Array

পাইথনের মধ্যে ম্যাথ ভালো করে সার্পোট দেয় কিন্তু array support দেয় না এর জন্য প্রথম ১৯৯৫ সালে jim hunguin numeric array create করে তারপর ২০০০ সালে space telescope science institute numarray create করে কিন্তু এগুলো ভালো ভাবে কাজ করচিল না ।

তারপর ২০০৫ সালে travis oliphant numeric array + numarray কে একসাথে করে numpy তৈরি করে ।


Array create করতে হলে আমাদের list আগে বানাতে হবে তারপর  টা np.array function এ পাস করতে হবে ।

list array এর তুলনায় ফাস্ট না ।


list এর মধ্যে অনেক ধরনের ডাঁটা রাখা যায় একসাথে কিন্তু array এর মধ্যে আমরা শুধু একধরনের Data রাখতে পারি ।

যদি আমরা অনেক ধরনের ডাঁটা রাখতে চাই তাহলে যদি string type এর Data থাকে তাহলে তাতে সবগুলো DAta স্ট্রিং এ convert হয়ে যাবে ।

যদি string না থেকে floating type value থাকে তাহলে তা floating এ convert হয়ে যাবে।

In [6]:
import numpy as np
list = [2,3,4,10] # list create
list


[2, 3, 4, 10]

In [7]:
array = np.array(list) # array create np.array(list)

In [8]:
listCheck = [2,3,421,'dibyo']
listCheck
variousDataTypeArray = np.array(listCheck)
variousDataTypeArray
# এখানে সব গুলো ডাঁটা element স্ট্রিং এ convert হয়ে যাবে ।

array(['2', '3', '421', 'dibyo'], dtype='<U21')

In [9]:
# floating datatype এ convert
ListCheck = [2,3,4.2, 53.52, 34.2002]
FloatingDAta = np.array(ListCheck)
FloatingDAta

array([ 2.    ,  3.    ,  4.2   , 53.52  , 34.2002])

# Vector And Matrix

vector One dimentional & Matrix Two Dimentional

list যদি one dimetional এর থেকে বেশি হয় কিন্তু তবু তা list ই থাকে matrix এ হয় কিন্তু vector তা matrix হয়ে যায় ।

আমরা vector  দিয়ে ম্যাট্রিক্স বানানো যায় ।


In [10]:
Dimentionallist = [[2343,2,43,51,12],[23,1,20,41,5] , [21,40,10,35,3]]
Dimentionallist  # এই যে এইটা list এর মত করেই output আসবে ।

[[2343, 2, 43, 51, 12], [23, 1, 20, 41, 5], [21, 40, 10, 35, 3]]

In [11]:
matrixx = np.array(Dimentionallist)
matrixx

array([[2343,    2,   43,   51,   12],
       [  23,    1,   20,   41,    5],
       [  21,   40,   10,   35,    3]])

# Array Generator


In [12]:
arrangeVector = np.arange(1,10) # start value , then last wanted value + 1
arrangeVector

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(1,11, 2) # 2 ঘর পরে পরে আসবে

array([1, 3, 5, 7, 9])

# Zero function

In [14]:
np.zeros(5) # 5 টা zero generated হবে

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((10,5)) # matrix আকারে আসবে ১০ টা row আর 5 টা কলাম আসবে ।

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# ones function

In [16]:
np.ones(5)# 5 টা one আসবে


array([1., 1., 1., 1., 1.])

In [17]:
np.ones((7,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# full function

If we want to Generate value not zero and one . Then we use full function

In [18]:
fullFunction = np.full(5,15)  # 5 টা col আর ১৫ ভ্যালু সেট হবে
fullFunction

array([15, 15, 15, 15, 15])

In [19]:
full_Function = np.full((2,5) , 11)
full_Function

array([[11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11]])

# Identity Function

Here diagonally value one হবে ।

In [20]:
np.eye(5,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

#  Linspace function




In [21]:
np.linspace(1,10,3)
# মানে ১ থেকে ১০ পর্যন্ত ভ্যালু আসবে কিন্তু ৩ টা আর টাদের মধ্যে distance সমান হবে

array([ 1. ,  5.5, 10. ])

In [22]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

# Random Function

> random.rand() function দিয়ে ১ থেকে ০ এর মধ্যে ভ্যালু আসবে its concept of normalisation .

> random.randn() function দিয়ে -৩ থেকে ৩ পর্যন্ত value  আসবে


> random.randint() function দিয়ে যে given value generate হবে।

> random.randint((startingValue , EndingValueValue) , howmanyValueGenerate)



In [23]:
np.random.rand(10)

array([0.01899408, 0.73900382, 0.79744796, 0.4686953 , 0.66891449,
       0.53118253, 0.8139061 , 0.98435979, 0.12181214, 0.62586206])

In [24]:
np.random.randn(20) # -3 theke 3 পর্যন্ত ভ্যালু আসবে।

array([-0.48472667,  0.42232115,  0.90536699,  1.35482909,  0.21978509,
        0.43366978,  1.17853113,  0.52486536, -0.02063464,  0.48082551,
        1.77463754,  1.07809249, -0.04748575,  1.17025808, -1.00218281,
       -0.97573437, -1.44058466,  1.93339223,  0.27029508,  0.30860118])

In [25]:
np.random.randint(5)

2

In [26]:
np.random.randint(2,10 ,20)

array([7, 5, 5, 3, 5, 9, 3, 7, 8, 9, 9, 3, 2, 2, 7, 5, 9, 6, 2, 8])

# Array Atribute


In [27]:
ar = np.array([[2,341,12] , [1,20,52] , [192,555,121]])
ar

array([[  2, 341,  12],
       [  1,  20,  52],
       [192, 555, 121]])

In [28]:
ar.size

9

In [29]:
ar.ndim # 2 dimentional show করবে।

2

In [30]:
ar.shape

(3, 3)

In [31]:
ar.dtype # datatype dekha jabe

dtype('int64')

# Data type change



In [32]:
arr = np.array([[23.21,52.10,2.2],[3.3,1.1,5.2]])
arr

array([[23.21, 52.1 ,  2.2 ],
       [ 3.3 ,  1.1 ,  5.2 ]])

In [33]:
arr = arr.astype(int)
arr

array([[23, 52,  2],
       [ 3,  1,  5]])

# Array Method

In [34]:
ar = np.arange(1,10)
ar

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
ar.max()

np.int64(9)

In [36]:
ar.min()

np.int64(1)

In [37]:
ar.sum()

np.int64(45)

In [38]:
ar.mean()

np.float64(5.0)

In [39]:
ar.argmax() # maximum element এর index

np.int64(8)

In [40]:
ar.argmin() # minimum element এর ইনডেক্স

np.int64(0)

# column wise & Row Wise  Sum & Reshape & Resizing

> np.sum(arr, axis = 0 ) its provide column wise elements total sum

> np.sum(arr, axis = 1 ) it’s provide row wise elements total sum .


In [41]:
ar = np.random.randint(10,30,30)
ar

array([20, 28, 12, 11, 12, 27, 27, 28, 12, 26, 15, 10, 18, 18, 13, 18, 26,
       14, 20, 11, 13, 22, 18, 21, 26, 16, 11, 24, 27, 10])

In [42]:
ar.reshape(5,6) # reshape kora hoyeche
ar = ar.reshape(5,6) # Resizing  (save করলে Resizing করা  হয় )

In [43]:
np.sum(ar, axis = 0) # column wise sum

array([111, 101,  61, 101,  98,  82])

In [44]:
np.sum(ar, axis = 1 ) # row wise sum

array([110, 118, 107, 105, 114])

# Ravel & flaten

ravel copy -
flaten

In [45]:
a = np.array([[2,3] , [4,2]])

In [46]:
a

array([[2, 3],
       [4, 2]])

In [47]:
b = a.ravel()
b[0] = 10

In [48]:
a # ei je ekhane a er man o change hoye jabe


array([[10,  3],
       [ 4,  2]])

In [49]:
b

array([10,  3,  4,  2])

In [50]:
b = a.flatten()
b[0] = 2203

In [51]:
b

array([2203,    3,    4,    2])

In [52]:
a

array([[10,  3],
       [ 4,  2]])

# Array Indexing &  Slicing




> ###### Array indexing এর মধ্যে দুইটা জিনিস থাকে একটা positive indexing & negative  Indexing .

> ###### Positive Indexing -> left to right value access করতে চাইলে।

> ###### Negative Indexing —> Right To Left value Access করতে চাইলে। Last element  দেখতে চাইলে -1 দিতে হবে।


In [53]:
a[0]

array([10,  3])

In [54]:
aa = np.arange(11,32)
aa

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31])

In [55]:
aa[1:5]

array([12, 13, 14, 15])

In [56]:
aa[:10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [57]:
aa[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31])

In [58]:
aa [ 3 : ]

array([14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
       31])

In [59]:
# যদি ভ্যালু গুলো কয়েক ঘর পর পর পেতে চাই তাহলে ::want এভাবে দিবো ।
aa [ 3 : : 2 ]

array([14, 16, 18, 20, 22, 24, 26, 28, 30])

In [60]:
# পিছনের থেকে ভ্যালু আসে।
aa [::-1]

array([31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11])

# Fancy Index

> একসাথে অনেক গুলো ইনডেক্স জানতে চাইলে



In [61]:
aa [[2,5,10]]

array([13, 16, 21])

# Indexing And Slicing Of Matrix

In [62]:
ar = np.arange(1,31) . reshape(5,6)
ar

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [63]:
# Find Row (Targeting Row)
ar[3]

array([19, 20, 21, 22, 23, 24])

In [64]:
ar[3,5]

np.int64(24)

In [65]:
slice = ar [0:3 , 3 : ]
slice

array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18]])

# Bool masking

In [66]:
ar = np.random.randint(10,30,30)
ar

array([23, 13, 29, 13, 29, 20, 10, 25, 23, 18, 22, 27, 25, 17, 28, 10, 10,
       24, 16, 11, 22, 20, 27, 26, 11, 17, 18, 19, 12, 17])

In [67]:
boolIndex = ar % 2 == 0
boolIndex

array([False, False, False, False, False,  True,  True, False, False,
        True,  True, False, False, False,  True,  True,  True,  True,
        True, False,  True,  True, False,  True, False, False,  True,
       False,  True, False])

In [68]:
evenVal = ar[boolIndex]
evenVal

array([20, 10, 18, 22, 28, 10, 10, 24, 16, 22, 20, 26, 18, 12])

# Array Operation


> a1 + a2 <br>
> a1 - a2 <br>
> a1 * a2 <br>
> a1 / a2 <br>
> a1 ** a2 (power) <br>

# New section

In [69]:
a1 = np.array([1,3,5,7])
a2 = np.array([2,4,6,8])

a1 + a2

array([ 3,  7, 11, 15])

In [70]:
a1 - a2

array([-1, -1, -1, -1])

In [71]:
a1 * a2

array([ 2, 12, 30, 56])

In [72]:
a1 ** a2

array([      1,      81,   15625, 5764801])

# BroadCasting


Broadcasting 3 rule :
	1. Matching Dimension  ( [1,2,5] + [3,4,5] = [4 , 6 , 10] <br>
	2. Expanding Single Element ( [1,2,3] + 10 = [11 ,12 , 13 ]<br>
	3. Incompatible Shape(shape match না করলে numpy error দিয়ে দিবে[১,৩,৫]+[১,৩] error)


In [73]:
a1 + 10

array([11, 13, 15, 17])

# Deep copy আর shallow  copy

Deep copy হত list এর মধ্যে যেখানে আমরা slice করে broadcasting / arithmetic operation করতাম তখন main list এ  change হয়ে যেত ।  <br><br>
But array এর মধ্যে হচ্ছে shallow copy এখানে আমরা slice করে নিলে আর সেখানে পরিবর্তন করলে আমাদের main array এর মধ্যে পরিবর্তন হবে না ।


Deep copy আর shallow  copy  <br>

Deep copy হত list এর মধ্যে যেখানে আমরা slice করে broadcasting / arithmetic operation করতাম তখন main list এ  change হয়ে যেত । <br> <br><br>
But array এর মধ্যে হচ্ছে shallow copy এখানে আমরা slice করে নিলে আর সেখানে পরিবর্তন করলে আমাদের main array এর মধ্যে পরিবর্তন হবে না ।




In [74]:
a = np.arange(1,31)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [75]:
slice = a[:5] * 2
slice

array([ 2,  4,  6,  8, 10])

In [76]:
a # ei je slice kore slice array te change koresi kintu main array te change hoy nai


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [77]:
b = a
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [78]:
b[0] = 22
b

array([22,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [79]:
a # ei je ekhane deep copy hoye giyeche
# jodi shalow copy kori tahole .copy() functiond diye dibo

array([22,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [80]:
b = a.copy()
b[0] = 32
a

array([22,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

# Matrix Operation

matrix multiplication a1 @ a2


# Array Advance Modification - Splict & Stack



We can’t stack two matrix we can stack two array / vector .  <br>
> Stack মনে দুইটা array / vector কে জোড়া লাগানো। <br>
আমরা stack তিনভাবে  করতে পারি :<br>
1. vertical stack -  np.vstack((a,b))
2. horizontal stack - np.hstack((a,b))
3. column_stack((a,b)) -  np.column_stack((a,b)) <br>



Split 2d array তে  থাকে।


সমান পার্ট এ করতে হবে split . 3 টা  করতে গেলে error আসবে।

# Stack

In [81]:
a = np.arange(10,26).reshape(4,4)
b = np.arange(30,46).reshape(4,4)
a

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [82]:
b

array([[30, 31, 32, 33],
       [34, 35, 36, 37],
       [38, 39, 40, 41],
       [42, 43, 44, 45]])

In [83]:
np.vstack((a,b))
# vertically add hobe .
#মানে একটা array  শেষ হলে আরেকটা array  শুরু হবে এভাবে
'''
a
b
'''

' \na\nb \n'

In [84]:
np.hstack((a,b))
# একটা array শেষ হওয়ার পর আরেকটা array শুরু হবে এভাবে
'''
a b
'''

' \na b \n'

In [85]:
np.column_stack((a,b)) # one kind of hstack এর মতো

array([[10, 11, 12, 13, 30, 31, 32, 33],
       [14, 15, 16, 17, 34, 35, 36, 37],
       [18, 19, 20, 21, 38, 39, 40, 41],
       [22, 23, 24, 25, 42, 43, 44, 45]])

# Split

In [86]:
c = np.arange(1,31).reshape(6,5)
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [87]:
np.hsplit(c,5) # এটা যেহেতু col number odd তাহলে এটা কে আমরা ৫ সমান ভাগে ভাগ করতে পারব না


[array([[ 1],
        [ 6],
        [11],
        [16],
        [21],
        [26]]),
 array([[ 2],
        [ 7],
        [12],
        [17],
        [22],
        [27]]),
 array([[ 3],
        [ 8],
        [13],
        [18],
        [23],
        [28]]),
 array([[ 4],
        [ 9],
        [14],
        [19],
        [24],
        [29]]),
 array([[ 5],
        [10],
        [15],
        [20],
        [25],
        [30]])]

In [88]:
np.vsplit(c,2)

[array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]),
 array([[16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]])]

# Array Insert , Append , Delete

- INSERT <br> np.insert(array, index, value)
আমরা কোন  array এর মধ্যে নতুন element insert করতে পারি  না কারণ তার সাইজ ফিক্সড থাকে । <br>
আমরা যখন insert operation চালাই তখন মেইন array এর কপি তৈরি হয়।

- Append <br>
Append at the end of the array element add হবে। <br>
 আর এখানেও নতুন array যেটা create হবে সেটা তে modification করলে  main array তে modification হবে না।
 - CONCATENATE <br>
 - Delete <br>


In [89]:
d = np.arange(10,110 , 10)
d

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [90]:
new_arr = d
new_arr = np.insert(new_arr , 2 , 203)
d

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [91]:
new_2d = np.arange(10,20).reshape((2,5))
NEW_2d = np.arange(10,30).reshape((4,5))
# NEW_2d
new_2d

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [92]:
nee = np.insert(new_2d,2,NEW_2d, axis = 0  )
nee

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [93]:
ap = np.append(new_2d , NEW_2d)
ap

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [94]:
con = np.concatenate((new_2d, NEW_2d) , )
con

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

# Handling Missing Value

> - np.isnan() Detecting Missing
this function return true Or false array
Value . nan - Not A Number <br>

> - np.isinf() Detecting Infinite Value <br>
> np.nan_to_num(array, nan = 100 ) default nan value replaced by 0 .
> np.nan_to_num(array, posinf = 10 , neginf = -10)



*italicised text*# New section

In [95]:
nanAr = np.array([1,2,3,np.nan, 4,10, np.nan, 123])
nanAr

array([  1.,   2.,   3.,  nan,   4.,  10.,  nan, 123.])

In [96]:
# check nan value
np.isnan(nanAr)

# np.nan == np.nan - We can't compary like this

array([False, False, False,  True, False, False,  True, False])

In [97]:
infAr = np.array([1,2,3,np.inf, - np.inf , 34,10, np.inf ])
infAr

array([  1.,   2.,   3.,  inf, -inf,  34.,  10.,  inf])

In [98]:
replaceArr = np.nan_to_num(nanAr , nan = 110)
replaceArr

array([  1.,   2.,   3., 110.,   4.,  10., 110., 123.])

In [99]:
replaceArrInf = np.nan_to_num(infAr, posinf= 10 , neginf=-10)
replaceArrInf

array([  1.,   2.,   3.,  10., -10.,  34.,  10.,  10.])

# Numpy Exercise

In [103]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])
dataa

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [104]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [106]:
# #Find the average age of students.

averageAge = data[:, 0].mean()
averageAge

np.float64(18.4)

In [107]:
#Extract Math marks of all students.
mathMark = data[:, 1]
mathMark

array([85, 92, 76, 65, 90])

In [108]:
#Find the highest Science mark.
highestMark =  data[:, 2].max()
highestMark

np.int64(95)

In [109]:
#Get details of the student who scored more than 90 in Math.
MoreThanNinetyMath = data[data[:, 1] > 90]
MoreThanNinetyMath

array([[19, 92, 88]])

In [111]:
# #Increase Math marks of all students by 5.

data[: , 1] += 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [112]:
#Find how many students are younger than 19.
len(data[data[:, 0] < 19])

3

In [113]:
#Calculate the average marks in each subject (column-wise mean).
MeanMark = data[:, 1:].mean(axis=0)
MeanMark

array([86.6, 83.2])

In [114]:
#Get data of students who scored at least 80 in both subjects.
data[(data[: , 1] >= 80) & (data[:,2] >= 80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [115]:
#Replace all Science marks < 75 with 0.
data[data[:, 2] < 75, 2] = 0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])